---
- name: Proxmox Configuration Playbook
  hosts: proxmox
  remote_user: root
  tasks:
    - name: Adding ansible SSH Pubkey as authorized
      ansible.builtin.copy:
        mode: "0600"
        src: ~/.ssh/authorized_keys
        dest: /root/.ssh/authorized_keys
    - name: Adding PVE-no-subscription repo
      ansible.builtin.blockinfile:
        path: /etc/apt/sources.list
        insertbefore: ^# security
        block: |
          # PVE pve-no-subscription repository provided by proxmox.com,
          # NOT recommended for production use
          deb http://download.proxmox.com/debian/pve bullseye pve-no-subscription
    - name: Upgrading system
      ansible.builtin.apt:
        upgrade: full
        update_cache: true
        cache_valid_time: 7200
    - name: Installing sudo
      ansible.builtin.apt:
        name: sudo
        state: present
